import type { Resource } from "@/types";

export const INDUSTRIES = [
  "Technology",
  "Healthcare",
  "Finance",
  "Marketing",
  "Sales",
  "Education",
  "Manufacturing",
  "Retail",
];

export const RESOURCES: Resource[] = [
  {
    id: "1",
    title: "AI for Everyone",
    type: "course",
    difficulty: "beginner",
    estimatedTime: 4,
    url: "https://www.coursera.org/learn/ai-for-everyone",
    description: "Comprehensive introduction to AI concepts, terminology, and applications",
  },
  {
    id: "2",
    title: "Machine Learning Crash Course",
    type: "course",
    difficulty: "beginner-intermediate",
    estimatedTime: 6,
    url: "https://developers.google.com/machine-learning/crash-course",
    description: "Practical introduction to machine learning concepts and tools",
  },
  {
    id: "3",
    title: "ChatGPT Complete Guide",
    type: "tutorial",
    difficulty: "beginner",
    estimatedTime: 2,
    url: "https://openai.com/blog/chatgpt",
    description: "Learn to use ChatGPT effectively for various tasks",
  },
  {
    id: "4",
    title: "GitHub Copilot Documentation",
    type: "documentation",
    difficulty: "beginner",
    estimatedTime: 1,
    url: "https://docs.github.com/en/copilot",
    description: "Official guide to using GitHub Copilot for coding assistance",
  },
  {
    id: "5",
    title: "Microsoft Copilot for Microsoft 365",
    type: "tutorial",
    difficulty: "beginner",
    estimatedTime: 1.5,
    url: "https://support.microsoft.com/en-us/copilot",
    description: "Learn to use Copilot in Microsoft Office applications",
  },
  {
    id: "6",
    title: "Prompt Engineering Guide",
    type: "guide",
    difficulty: "beginner-intermediate",
    estimatedTime: 3,
    url: "https://www.promptingguide.ai/",
    description: "Comprehensive guide to writing effective prompts for AI systems",
  },
  {
    id: "7",
    title: "Advanced Prompt Engineering",
    type: "course",
    difficulty: "intermediate-advanced",
    estimatedTime: 4,
    url: "https://learnprompting.org/",
    description: "Advanced techniques for complex AI interactions",
  },
  {
    id: "8",
    title: "AI Ethics: A Guide for Business Leaders",
    type: "guide",
    difficulty: "intermediate",
    estimatedTime: 2,
    url: "https://www.ibm.com/artificial-intelligence/ethics",
    description: "Understanding ethical considerations in AI implementation",
  },
  {
    id: "9",
    title: "Responsible AI Practices",
    type: "course",
    difficulty: "intermediate",
    estimatedTime: 3,
    url: "https://cloud.google.com/learn/responsible-ai",
    description: "Best practices for implementing AI responsibly in organizations",
  },
  {
    id: "10",
    title: "AI for Business Leaders",
    type: "course",
    difficulty: "beginner-intermediate",
    estimatedTime: 5,
    url: "https://www.coursera.org/learn/ai-for-business",
    description: "How AI can transform business operations and strategy",
  },
  {
    id: "11",
    title: "MCP (Model Context Protocol) Documentation",
    type: "documentation",
    difficulty: "intermediate",
    estimatedTime: 2,
    url: "https://modelcontextprotocol.io/",
    description: "Official documentation for MCP — a protocol for AI models to access external data and tools",
  },
  {
    id: "12",
    title: "Building MCP Servers",
    type: "tutorial",
    difficulty: "intermediate-advanced",
    estimatedTime: 4,
    url: "https://modelcontextprotocol.io/docs/servers",
    description: "Learn how to build custom MCP servers to extend AI model capabilities",
  },
  {
    id: "13",
    title: "MCP Client Integration",
    type: "guide",
    difficulty: "intermediate",
    estimatedTime: 3,
    url: "https://modelcontextprotocol.io/docs/clients",
    description: "How to integrate MCP clients into your AI applications",
  },
  {
    id: "14",
    title: "MCP GitHub Repository",
    type: "repository",
    difficulty: "intermediate",
    estimatedTime: 2,
    url: "https://github.com/modelcontextprotocol",
    description: "Official MCP GitHub repository with examples and implementations",
  },
  {
    id: "15",
    title: "MCP Server Examples",
    type: "examples",
    difficulty: "intermediate",
    estimatedTime: 3,
    url: "https://github.com/modelcontextprotocol/servers",
    description: "Collection of example MCP servers for various use cases",
  },
  {
    id: "16",
    title: "MCP Best Practices",
    type: "guide",
    difficulty: "intermediate-advanced",
    estimatedTime: 2,
    url: "https://modelcontextprotocol.io/docs/best-practices",
    description: "Best practices for building and deploying MCP servers",
  },
  {
    id: "17",
    title: "MCP Security Guide",
    type: "guide",
    difficulty: "intermediate",
    estimatedTime: 2,
    url: "https://modelcontextprotocol.io/docs/security",
    description: "Security considerations and best practices for MCP implementations",
  },
];
